### ISSUE TITLE
ysp VideoPlayer plugin freezes the game

### ISSUE THREAD

**Issue by saikedemon** [rphsoftware/OneLoader#2]
An issue that affects both mods and the vanilla game, any event/cutscene that calls the ysp VideoPlayer plugin command (in example, 'ysp.VideoPlayer.loadVideo('Bad End Credits Draft 4.webm')') freezes the game. I do not know if it is from a specific command or just the plugin in general. Both the vanilla game and GOMORI are exempt from this issue.

**Comment by rphsoftware** [comment]
Initial triage:
In an isolated environment with the same nw.js version, intercepted requests for videos always get aborted. On latest nw, that bug is not present, which means this bug is rooted somewhere in the underlying runtime (Chrome 65/nw 0.29). Workaround ideas will be explored and reported back on.

**Comment by rphsoftware** [comment]
Triage followup:
Without updating chromium, it's impossible for media request to succeed when using Network Request Interception, which means that the proper fix will be overriding document.createElement or PIXI's VideoBaseTexture.fromUrl method to directly access the VFS

**Comment by rphsoftware** [comment]
The issue appears to be mostly resolved by 7a8c386, though I will keep this issue open until more testing is done on Preview 3.1

Please go and test the latest release (Preview 3.1) and close this issue if you consider it fixed
